### PR TITLE
Update to 115.0 on beta channel

### PR DESCRIPTION
**Pull request by mfschumann**
This PR prepares the update to the stable 115.0 release. It will stay on the flathub beta channel until stability is deemed ok or 102 is EOL, whichever is earlier.

### CODE REVIEW

**Comment by mfschumann** [comment]
Test results for the application extensions:

- On a pristine profile the BB 115 lang packs are picked up fine.

- On an existing profile migrated from BB 102 the application extension lang packs for BB 115 are shadowed by the incompatible user extension lang packs from BB 102. After removing the BB 102 lang packs (through the UI) and restarting BB the BB 115 lang packs are picked up.

I am going to test how profile migration works when sticking with distribution extension lang packs instead.

**Comment by mfschumann** [comment]
Test results for **distribution** extensions:
* On a pristine profile lang packs are picked up fine.
* On an existing profile migrated from BB 102 the lang packs are automatically updated to the BB 115 version.

That means upgrading from 102 to 115 is smoother when we stick with distribution extension lang packs. The only downside I can see: If a user previously uninstalled a language pack for a profile through the UI, it will not come back for that profile. @Betterbird Any thoughts on this?

**Comment by Betterbird** [comment]
> Any thoughts on this?

Yes. Distribution extensions suck terribly as a long litany of problems with TB's Lightning distribution extension showed. It's not only that de-installation will forever prevent the distribution re-installation. Also installing an extension manually will forever break the distribution extension upgrade path.

I would switch to application extensions and tell the users to remove the defunct old ones manually. If that's too hard, we could even implement suppressing incompatible old language packs programmatically (although I prefer not to).

Shipping anything as distribution extension was a mistake to start with, and we'll never fix it if we don't take a clear cut now.

**Comment by mfschumann** [comment]
Ok, then let's go with application extensions starting with 115.0.

I am not sure how we should inform users about the change. I will add a paragraph in the Readme of this repo, but most users won't see this before they upgrade. Do you think a note on the BB website or some kind of notification in BB would make sense?

**Comment by Betterbird** [comment]
We'll put something onto the release notes, which also people won't read :wink:

**Comment by Betterbird** [comment]
What about putting a note here:
https://flathub.org/apps/eu.betterbird.Betterbird
Under Changes in version 115.0 ...
We're switching language pack from distribution extensions to application extensions.
Please delete the outdated language packs from Betterbird 102.

**Comment by mfschumann** [comment]
Interesting. I cannot reproduce this behavior with the flatpak'ed 115.0-bb6-build3. Can this bug be Windows-specific?

**Comment by Betterbird** [comment]
Well, if you look at the console, it first says that the old language pack is incompatible, but soon after, it springs back to life. Maybe because I have the language configured as alternative language. Anyway, we can't run the risk that this will blow up, so:

https://github.com/Betterbird/thunderbird-patches/blob/main/115/misc/08b-misc-disable-BB-langpacks-m-c.patch

**Pull request merged**
