### PR TITLE
build for aarch64

### PR DESCRIPTION
**Pull request by mfschumann**

### CODE REVIEW

**Comment by mfschumann** [comment]
bot, build

**Comment by mfschumann** [comment]
@dbonner Do you happen to have an aarch64 box where you could test the above flatpak? It seems the build was successful on first try.

On Debian/Ubuntu all you need to do is
```
apt install -y flatpak
flatpak install --user https://dl.flathub.org/build-repo/106913/eu.betterbird.Betterbird.flatpakref
```

**Comment by dbonner** [comment]
@mfschumann Yes I will test it 👍

**Comment by dbonner** [comment]
@mfschumann
Yes, the flatpak aarch64 build works on my aarch64 build machine (a c7g.4xlarge aarch64 Amazon EC2 instance running Debian Bullseye).  I ran it in xfce4 and VNC'ed in to the instance from home.  I really like the idea of flatpak or snap packages, because they run on all sorts of different distros.  Sadly flatpak and snap builds do not work in a proot environment. My main interest in aarch64 builds is to run them in a proot environment (termux in unrooted Android tablets or phablets).  My conventional builds work in proot (and also work in conventional aarch64 boxes). Anyhow, well done in creating the flatpak ... It's all thumbs up from me!

**Pull request merged**
